service: selenium-lambda

provider:
  name: aws
  profile: ${env:AWS_PROFILE, 'profile-name'}
  region: ${env:AWS_REGION, 'eu-west-1'}
  stage: 'prod'
  ecr:
    images:
      img:
        path: ./
        platform: linux/amd64

functions:
  f_example:
    timeout: 60
    memorySize: 2048
    image:
      name: img